name: Validate Changes

on:
  workflow_dispatch:
  pull_request:


defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
            version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm build